### ISSUE TITLE
Solution breaks ability to use Custom Controls

### ISSUE THREAD

**Issue by DREWLFE** [drivardxrm/CountryPicker.PCF#1]
After installing either of the provided solutions I get a blank box when trying to add a custom control and have to uninstall the solution in order to add any sort of control to a text box afterwards.
Looks like the issue described on: https://powerusers.microsoft.com/t5/Power-Apps-Component-Framework/All-controls-disappear-from-Add-Control-Dialog-after-importing/td-p/390445

**Comment by drivardxrm** [comment]
Hi, that is weird, I remember seeing this behavior in the past. I will have a look at it shortly.
Thanks for the catch.

**Comment by drivardxrm** [comment]
Hi, I published a new release of the component.
There was some single quotes in the manifest descriptions that was causing the bug.
Its weird that i was able to pac push in my test environment without any issues.

Can you confirm that it is now working with this new release. Thanks

![image](https://user-images.githubusercontent.com/38399134/75897684-f2877600-5e06-11ea-9032-7100bcbad691.png)

**Comment by DREWLFE** [comment]
Hi, I downloaded 1.0.0.1 and it's working great.  Fantastic component, thanks very much
