### ISSUE TITLE
Error Fetching data API Offline

### ISSUE THREAD

**Issue by MattCollins-Jones** [drivardxrm/CountryPicker.PCF#11]
We use this PCF component in a few places and noticed an error saying "Error Fetching data". 

![errorCountryPicker](https://user-images.githubusercontent.com/60160115/134499687-2bce3086-e148-4e47-bc94-8418f75751ca.png)

I took a look at the API listed and it looks like it's got a 504 bad gateway error, so i'm assuming it's offline. I'm not sure if this is prone to going offline or if it's going offline permanently, I just wanted to raise it. I appreciate you have no control over the API and it's just a public one, but thought it might be something you want to investigate or switch to another API source.

**Comment by drivardxrm** [comment]
Hi @MattCollins-Jones That is a big problem indeed ;(.
I guess I have no choice than to refactor the control and inject the free API key in the inputs.

Will try to work on it ASAP

**Comment by drivardxrm** [comment]
@MattCollins-Jones @joslange 
The free tier of the new API is very bad. 100 call per month 😡
![image](https://user-images.githubusercontent.com/38399134/135314459-c19b9fcc-24b9-47f1-b1ff-67ff2010d526.png)

I might have to find another source API

**Comment by drivardxrm** [comment]
@MattCollins-Jones 
I think I found the issue, while looking at the [doc](https://restcountries.com) they changed the api version to 3.1
Ex. This call will still work like before : [https://restcountries.com/v3.1/all](https://restcountries.com/v3.1/all)

The control uses https://restcountries.eu/rest/v2/all that looks discontinued
I will update ASAP

**Comment by joslange** [comment]
> @MattCollins-Jones @joslange I published a new release v1.0.0.8 seems that the base urll i was using for the API call is not working anymore (https://restcountries.eu) changed to https://restcountries.com and all seems back to normal.

Quickly tested an upgrade in one environment, can confirm that it seems to be working just fine. Thanks for the quick response! :)

**Comment by drivardxrm** [comment]
Closing the issue
