### ISSUE TITLE
Flags arn't displayed anymore

### ISSUE THREAD

**Issue by BenjaminChesnel** [drivardxrm/CountryPicker.PCF#12]
Hello,

On my environnements the flags aren't displayed anymore there is an error in the web browser console for each country which mean that the .svg file of the country isn't available on "restcountries.com" (or the URI changed).

Thank you for your help.

Best regards,

Benjamin.

**Comment by drivardxrm** [comment]
Hi @BenjaminChesnel , I published a new release that fixes the issue.
[v1.0.0.9](https://github.com/drivardxrm/CountryPicker.PCF/releases/latest)

**Comment by drivardxrm** [comment]
fixed in release v1.0.0.9
