### ISSUE TITLE
Official vs Common Name

### ISSUE THREAD

**Issue by bwmodular** [drivardxrm/CountryPicker.PCF#24]
This is a great tool - thanks for developing it! Really Useful.

I don't quite understand why, for some countries, it displays the 'Common' name rather than the Official Name (eg Jordan rather than "Hashemite Kingdom of Jordan"), but for the UK it displays "United Kingdom of Great Britain and Northern Ireland" rather than "United Kingdom".
No-one would ever call it that in practice, and it's not (for example) what would be written in the address.
We would just put the common name: "United Kingdom". I couldn't see a way to control this, but I think most UK users would immediately be put off by this...

**Comment by drivardxrm** [comment]
@bwmodular you are right, I noticed that too regarding UK, the name seems odd to me.

The service used to fetch the countries is RestCountries v2 of the API (They are on v3 now but I never updated the control), i'm afraid of breaking changes to current users of the control.

If you check at the output for UK in API v2, "United Kingdom of Great Britain and Northern Ireland" is the name that they give. I see that the 'native name' could be used but this would break for other countries.

![image](https://github.com/drivardxrm/CountryPicker.PCF/assets/38399134/884222d2-52b5-4dac-9fb4-628a19306b90)

On the other hand, if I look at the v3 output, they give the common name and the long name
I get this for UK 
![image](https://github.com/drivardxrm/CountryPicker.PCF/assets/38399134/d95e1385-a5fd-4611-9b85-bb6d310e8670)

I think I will make the switch soon to v3 and put a disclaimer for existing users

Thanks for your feedback

**Comment by drivardxrm** [comment]
Hi @bwmodular 
I finally found some time to upgrade the control to the latest version of the Rest Countries API

You"ll be happy to find a more decent rendering for the UK ;)
![image](https://github.com/drivardxrm/CountryPicker.PCF/assets/38399134/435b652d-1e54-4936-95fd-bd2595a8557a)

**Comment by bwmodular** [comment]
Wonderful, thanks for doing this, and thanks for letting me know.

Best wishes,
Ben
